"""Auto generated

Revision ID: 4c4cb56442a9
Revises: fe94d60449f2
Create Date: 2022-11-19 14:16:04.956922

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4c4cb56442a9"
down_revision = "fe94d60449f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("queues", sa.Column("delivery_delay_seconds", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("queues", "delivery_delay_seconds")
    # ### end Alembic commands ###
