name: Execute lint/tests/release

on:
  push:
    branches:
      - main

env:
  FASTQUEUE_DATABASE_URL: "postgresql+psycopg2://fastqueue:fastqueue@localhost:5432/fastqueue-test"

jobs:
  build:
    uses: ./.github/workflows/lint-and-tests.yml
  release-please:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
          package-name: fastqueue
